// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Context;

namespace Project.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20211130093820_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Project.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayClubName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AwayFinalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayNumberOfTD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeClubName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeFinalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeNumberOfTD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
